apply plugin: 'application'

project.version = '1.0'

project.ext.distVersion = System.getProperty("version", "SNAPSHOT");

repositories {
    mavenLocal()
    mavenCentral()

    repositories {
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
}

sourceSets {
    main.resources.srcDirs = ['src']
}

run {
    mainClassName = 'php.runtime.launcher.Launcher'
    jvmArgs += ["-Dfile.encoding=UTF-8", "-Xms256m", "-Xms1280m"]
}

jar.archiveName = 'DevelNext.jar'

clean {
    delete = [] //clear out existing files to delete
    delete 'build/install', 'build/libs', 'build/tmp', 'build/resources', 'build/scripts'
}

manifest {
    attributes 'Main-Class': 'org.develnext.jphp.ext.javafx.FXLauncher'
}

def buildISS = { issFile ->
    def innoSetupBin = "$project.rootDir/develnext-tools/innoSetup/ISCC.exe".replace("\\", "/")

    if (System.properties['os.name'].toLowerCase().contains('linux')) {
        exec {
            commandLine 'wine', innoSetupBin, '/Qp', issFile
        }
    } else {
        exec {
            commandLine innoSetupBin, '/Qp', issFile
        }
    }
}

def makeExe = { file ->
    if (System.properties['os.name'].toLowerCase().contains('windows')) {
        exec {
            commandLine "$project.rootDir/develnext-tools/Launch4j/launch4jc.exe"
            args file
        }
    } else if (System.properties['os.name'].toLowerCase().contains('linux')) {
        new File("$project.rootDir/develnext-tools/Launch4jLinux/launch4j").setExecutable(true, true);
        new File("$project.rootDir/develnext-tools/Launch4jLinux/bin/windres").setExecutable(true, true);
        new File("$project.rootDir/develnext-tools/Launch4jLinux/bin/ld").setExecutable(true, true);

        exec {
            commandLine "$project.rootDir/develnext-tools/Launch4jLinux/launch4j"
            args file
        }
    }
}

task prepareDist(dependsOn: ['installDist']) {
    doLast {
        fileTree("$project.buildDir/install/$project.name/lib").visit { FileVisitDetails el ->
            def name = el.getName()
            name = name.replaceAll(/(-[0-9]+|\.[0-9]+|-SNAPSHOT)/, "");

            if (name.startsWith("develnext-control-")) {
                el.file.delete();
            } else {
                if (!name.equals(el.getName())) {
                    println "Rename '" + el.file.parent + "/" + name + "' file"

                    if (name == "develnext-launcher.jar") {
                        copy {
                            from el.file
                            into "$project.buildDir/install/$project.name"
                            rename(/develnext-launcher-.*\.jar/, "DevelNext.jar")
                        }

                        el.file.delete();
                        el.file.deleteOnExit();
                    } else {
                        el.file.renameTo(file(el.file.parent + "/" + name));
                    }
                }
            }
        }
    }
}

task distWindowsPatch(type: Zip, dependsOn: ['clean', 'distPatch']) {
    from "$project.buildDir/install/$project.name"
    archiveName "DevelNext.WindowsPatch-${project.ext.distVersion}.zip"

    doLast {
        def issFile = "$project.rootDir/develnext/windowsSetup/innopatchsetup.iss".replace("\\", "/")

        if (System.properties['os.name'].toLowerCase().contains('linux')) {
            issFile = "windowsSetup/innopatchsetup.iss"
        }

        buildISS(issFile)

        file("$project.buildDir/distributions/DevelNext.WindowsPatch-${project.ext.distVersion}.exe").delete()

        file("$project.buildDir/distributions/DevelNext.WindowsPatch.exe")
                .renameTo(file("$project.buildDir/distributions/DevelNext.WindowsPatch-${project.ext.distVersion}.exe"))
    }
}

task distLinuxPatch(type: Tar, dependsOn: ['clean', 'distPatch']) {
    def installDir = "$project.buildDir/install/$project.name"

    compression = Compression.GZIP
    archiveName "DevelNext.LinuxPatch-${project.ext.distVersion}.tar.gz"

    from(installDir) {
        exclude('*.sh')
        exclude('DevelNext')
        exclude('DevelNext.jar')
        exclude('bin/develnext')
        exclude('tools/apache-ant/bin/ant')
        //exclude('tools/gradle/bin/gradle')
        exclude('tools/jre/bin/java')
        exclude('tools/Launch4jLinux/launch4j')
        exclude('tools/Launch4jLinux/bin/windres')
        exclude('tools/Launch4jLinux/bin/ld')
    }

    from(installDir) {
        include('*.sh')
        include('DevelNext')
        include('DevelNext.jar')
        include('bin/develnext')
        include('tools/apache-ant/bin/ant')
        //include('tools/gradle/bin/gradle')
        include('tools/jre/bin/java')
        include('tools/Launch4jLinux/launch4j')
        include('tools/Launch4jLinux/bin/windres')
        include('tools/Launch4jLinux/bin/ld')

        fileMode = 0755
    }

    doLast {
        def uploadPath = System.getProperty("uploadPath", "E:/Upload")

        if (new File(uploadPath).isDirectory()) {
            copy {
                from distLinuxPatch.archivePath
                into "$uploadPath/YandexDisk"
            }
        }
    }
}


task distPatch(dependsOn: ['prepareDist']) {
    doLast {
        if (System.properties['os.name'].toLowerCase().contains('windows')) {
            exec {
                commandLine "$project.rootDir/develnext-tools/Launch4j/launch4jc.exe"
                args "$project.rootDir/develnext/launcher/winLauncher.xml"
            }
        }

        copy {
            from "$project.rootDir/develnext/launcher/DevelNext.exe"
            into "$project.buildDir/install/$project.name"
        }

        copy {
            from "$project.rootDir/develnext/misc"
            into "$project.buildDir/install/$project.name"
        }
    }
}



task distIdeWindows(dependsOn: ['distIde']) {
    doLast {
        delete "$project.buildDir/install/$project.name/tools/jre"
        delete "$project.buildDir/install/$project.name/tools/Launch4j"
        delete "$project.buildDir/install/$project.name/tools/Launch4jLinux"

        copy {
            from "$project.rootDir/develnext-tools/jre"
            into "$project.buildDir/install/$project.name/tools/jre"
        }

        copy {
            from "$project.rootDir/develnext-tools/Launch4j"
            into "$project.buildDir/install/$project.name/tools/Launch4j"
        }
    }
}

task distIdeLinux(dependsOn: ['distIde']) {
    doLast {
        delete "$project.buildDir/install/$project.name/tools/jre"
        delete "$project.buildDir/install/$project.name/tools/Launch4j"
        delete "$project.buildDir/install/$project.name/tools/Launch4jLinux"

        copy {
            from "$project.rootDir/develnext-tools/jreLinux"
            into "$project.buildDir/install/$project.name/tools/jre"
        }

        copy {
            from "$project.rootDir/develnext-tools/Launch4jLinux"
            into "$project.buildDir/install/$project.name/tools/Launch4jLinux"
        }
    }
}

task distIde(dependsOn: ['prepareDist']) {
    doLast {
        makeExe("$project.rootDir/develnext/launcher/winLauncher.xml")
        makeExe("$project.rootDir/develnext/launcher/winLauncher-debug.xml")

        copy {
            from "$project.rootDir/develnext-tools"
            into "$project.buildDir/install/$project.name/tools"
            exclude "gradle"
            exclude "jre"
            exclude "jreLinux"
            exclude "Launch4j"
            exclude "Launch4jLinux"
        }

        copy {
            from "$project.rootDir/develnext/launcher/DevelNext.exe"
            into "$project.buildDir/install/$project.name"
        }

        copy {
            from "$project.rootDir/develnext/launcher/DevelNext-debug.exe"
            into "$project.buildDir/install/$project.name"
        }

        copy {
            from "$project.rootDir/develnext/misc"
            into "$project.buildDir/install/$project.name"
        }
    }
}

task distIdeWindowsSetup(dependsOn: ['clean', 'distIdeWindows']) {
    doLast {
        def issFile = "$project.rootDir/develnext/windowsSetup/innosetup.iss".replace("\\", "/")

        if (System.properties['os.name'].toLowerCase().contains('linux')) {
            issFile = 'windowsSetup/innosetup.iss'
        }

        buildISS(issFile);


        file("$project.buildDir/distributions/DevelNextSetup-${project.ext.distVersion}.exe").delete()

        file("$project.buildDir/distributions/DevelNextSetup.exe")
                .renameTo(file("$project.buildDir/distributions/DevelNextSetup-${project.ext.distVersion}.exe"))
    }
}

task distIdeWindowsArchive(type: Zip, dependsOn: ['clean', 'distIdeWindows']) {
    def installDir = "$project.buildDir/install/$project.name"
    def timeStamp = new Date().format("dd-MM-yyyy-HH-mm")

    archiveName "DevelNextWindows-${project.ext.distVersion}.${timeStamp}.zip"
    includeEmptyDirs true

    from installDir
}

task distIdeWindowsArchiveWithoutJRE(type: Zip, dependsOn: ['clean', 'distIdeWindows']) {
    doFirst {
        delete "$project.buildDir/install/$project.name/tools/jre"
    }

    def installDir = "$project.buildDir/install/$project.name"
    def timeStamp = new Date().format("dd-MM-yyyy-HH-mm")

    archiveName "DevelNextWindows-${project.ext.distVersion}.${timeStamp}.Without-JRE.zip"
    includeEmptyDirs true

    from installDir
}

task distIdeLinuxSetupWithoutJRE(type: Zip, dependsOn: ['clean', 'distIdeLinux']) {
    doFirst {
        delete "$project.buildDir/install/$project.name/tools/jre"
    }

    def installDir = "$project.buildDir/install/$project.name"
    def timeStamp = new Date().format("dd-MM-yyyy-HH-mm")

    archiveName "DevelNextLinux-${project.ext.distVersion}.${timeStamp}.Without-JRE.zip"
    includeEmptyDirs true

    from(installDir) {
        exclude('*.sh')
        exclude('DevelNext')
        exclude('DevelNext.jar')
        exclude('bin/develnext')
        exclude('tools/apache-ant/bin/ant')
        //exclude('tools/gradle/bin/gradle')
        exclude('tools/jre/bin/java')
        exclude('tools/Launch4jLinux/launch4j')
        exclude('tools/Launch4jLinux/bin/windres')
        exclude('tools/Launch4jLinux/bin/ld')
    }

    from(installDir) {
        include('*.sh')
        include('DevelNext')
        include('DevelNext.jar')
        include('bin/develnext')
        include('tools/apache-ant/bin/ant')
        //include('tools/gradle/bin/gradle')
        include('tools/jre/bin/java')
        include('tools/Launch4jLinux/launch4j')
        include('tools/Launch4jLinux/bin/windres')
        include('tools/Launch4jLinux/bin/ld')

        fileMode = 0755
    }
}


task distIdeLinuxSetup(type: Tar, dependsOn: ['clean', 'distIdeLinux']) {
    def installDir = "$project.buildDir/install/$project.name"

    compression = Compression.GZIP
    archiveName "DevelNextLinux-${project.ext.distVersion}.tar.gz"

    from(installDir) {
        exclude('*.sh')
        exclude('DevelNext')
        exclude('DevelNext.jar')
        exclude('bin/develnext')
        exclude('tools/apache-ant/bin/ant')
        //exclude('tools/gradle/bin/gradle')
        exclude('tools/jre/bin/java')
        exclude('tools/Launch4jLinux/launch4j')
        exclude('tools/Launch4jLinux/bin/windres')
        exclude('tools/Launch4jLinux/bin/ld')
    }

    from(installDir) {
        include('*.sh')
        include('DevelNext')
        include('DevelNext.jar')
        include('bin/develnext')
        include('tools/apache-ant/bin/ant')
        //include('tools/gradle/bin/gradle')
        include('tools/jre/bin/java')
        include('tools/Launch4jLinux/launch4j')
        include('tools/Launch4jLinux/bin/windres')
        include('tools/Launch4jLinux/bin/ld')

        fileMode = 0755
    }
}

// Unlike tools/jre and tools/jreLinux, the mac JRE isn't checked into git: its WebKit
// dylib alone is 138MB, over GitHub's 100MB hard limit, and this repo is a fork (GitHub
// blocks Git LFS uploads to forks without purchased storage). Fetched on demand instead.
task fetchMacJre {
    def jreMacDir = file("$project.rootDir/develnext-tools/jreMac")
    def zuluBuild = 'zulu8.94.0.17-ca-fx-jdk8.0.492-macosx_aarch64'

    outputs.dir jreMacDir

    onlyIf { !jreMacDir.directory }

    doLast {
        def archive = File.createTempFile('zulu8fx', '.tar.gz')
        def extractDir = File.createTempDir('zulu8fx', 'extracted')

        try {
            println "Downloading $zuluBuild ..."
            ant.get(src: "https://cdn.azul.com/zulu/bin/${zuluBuild}.tar.gz", dest: archive)

            exec { commandLine 'tar', 'xzf', archive.path, '-C', extractDir.path }

            jreMacDir.parentFile.mkdirs()
            def jreSrc = file("${extractDir}/${zuluBuild}/Contents/Home/jre")
            jreSrc.renameTo(jreMacDir)
        } finally {
            archive.delete()
            extractDir.deleteDir()
        }
    }
}

task distIdeMac(dependsOn: ['fetchMacJre', 'distIde']) {
    doLast {
        delete "$project.buildDir/install/$project.name/tools/jre"
        delete "$project.buildDir/install/$project.name/tools/Launch4j"
        delete "$project.buildDir/install/$project.name/tools/Launch4jLinux"

        copy {
            from "$project.rootDir/develnext-tools/jreMac"
            into "$project.buildDir/install/$project.name/tools/jre"
        }
    }
}

// Builds the .app/.dmg directly from distIde's output (not distIdeMac's), so tools/jre
// is never copied into the input tree -- the mac JRE is supplied once, as the jpackage
// runtime image, instead of being duplicated inside the app bundle too.
task distIdeMacDmg(dependsOn: ['fetchMacJre', 'clean', 'distIde']) {
    doLast {
        def installDir = "$project.buildDir/install/$project.name"
        def distDir = "$project.buildDir/distributions"

        def jpackageBin = System.getProperty("jpackage.bin", "jpackage")
        def appVersion = (project.ext.distVersion =~ /\d+(\.\d+)*/)[0] ?: '1.0'

        file(distDir).mkdirs()

        exec {
            // DevelNext.jar (built by prepareDist) carries a Class-Path manifest entry
            // pointing at ../lib/*.jar, the same way develnext/misc/DevelNext's plain
            // `java -jar DevelNext.jar` launch already relies on for Linux -- so --input
            // is the whole install dir (jar + lib/ side by side), not just lib/.
            commandLine jpackageBin,
                    '--type', 'dmg',
                    '--name', 'DevelNext',
                    '--input', installDir,
                    '--main-jar', 'DevelNext.jar',
                    '--runtime-image', "$project.rootDir/develnext-tools/jreMac",
                    '--icon', "$project.rootDir/develnext/launcher/DevelNext.icns",
                    '--mac-package-identifier', 'org.develnext.ide',
                    '--app-version', appVersion,
                    '--dest', distDir
        }
    }
}

// Mirrors fetchMacJre, but for a Java 11 + JavaFX runtime: BellSoft's Liberica Full JDK 11
// bundles JavaFX ("LibericaFX") the same way Zulu 8 FX does for Java 8. Unlike Java 8, Java
// 9+ has no separate slim "JRE" package -- bundling means bundling the whole JDK.
task fetchJre11Mac {
    def jre11MacDir = file("$project.rootDir/develnext-tools/jre11Mac")
    def libericaBuild = 'bellsoft-jdk11.0.31+11-macos-aarch64-full'

    outputs.dir jre11MacDir

    onlyIf { !jre11MacDir.directory }

    doLast {
        def archive = File.createTempFile('liberica11fx', '.tar.gz')
        def extractDir = File.createTempDir('liberica11fx', 'extracted')

        try {
            println "Downloading $libericaBuild ..."
            ant.get(src: "https://github.com/bell-sw/Liberica/releases/download/11.0.31+11/${libericaBuild}.tar.gz", dest: archive)

            exec { commandLine 'tar', 'xzf', archive.path, '-C', extractDir.path }

            jre11MacDir.parentFile.mkdirs()
            // Unlike Zulu 8's macOS bundle (<build>/Contents/Home/jre), Liberica's tarball is a
            // flat JDK layout with bin/, lib/, etc. directly under the top-level dir -- no
            // Contents/Home wrapper (confirmed by inspecting the actual archive contents).
            def jdkSrc = file("${extractDir}/jdk-11.0.31-full.jdk")
            jdkSrc.renameTo(jre11MacDir)
        } finally {
            archive.delete()
            extractDir.deleteDir()
        }
    }
}

// OpenJFX jars actually bundled into the packaged app's lib/ folder (unlike the same
// artifacts declared `provided` in the root build.gradle, which are compile-time only).
// Liberica Full JDK bundles its own JavaFX as JPMS modules, but this app is a plain
// classpath application (DevelNext.jar's Class-Path manifest entry lists lib/*.jar), so it
// needs JavaFX as ordinary jars on that same classpath rather than relying on the runtime
// image's module path.
configurations {
    javaFx11Runtime
}

dependencies {
    // transitive = false: each org.openjfx:*:mac artifact's own POM depends on the matching
    // non-classified (no-native-libs) artifact, e.g. javafx-controls:11.0.2:mac -> javafx-base:
    // 11.0.2 with no classifier. Left transitive, both the real -mac jar and that native-less
    // stub end up side by side on lib/*'s wildcard classpath -- a split-package conflict where
    // whichever jar the classloader picks first may be the one missing native bindings, which
    // was observed to hang JavaFX's native toolkit init silently instead of failing loudly.
    // Every module actually needed is already listed explicitly below, so nothing is lost by
    // turning transitivity off.
    ['base', 'graphics', 'controls', 'fxml', 'media', 'swing', 'web'].each { module ->
        javaFx11Runtime("org.openjfx:javafx-$module:11.0.2:mac") { transitive = false }
    }
}

task distIdeMacJava11Dmg(dependsOn: ['fetchJre11Mac', 'clean', 'distIde']) {
    doFirst {
        if (project.ext.javaTarget != '11') {
            throw new GradleException("distIdeMacJava11Dmg must be run with -PjavaTarget=11 (was '${project.ext.javaTarget}')")
        }
    }

    doLast {
        def installDir = "$project.buildDir/install/$project.name"
        def distDir = "$project.buildDir/distributions"

        def jpackageBin = System.getProperty("jpackage.bin", "jpackage")
        // Not `(distVersion =~ pattern)[0]` (as distIdeMacDmg above does): with a capturing
        // group in the pattern, that indexing returns [wholeMatch, lastGroup] as a List, not a
        // String -- jpackage would then get literally "[1.0.0, .0]" as --app-version.
        def versionMatcher = project.ext.distVersion =~ /\d+(\.\d+)*/
        def appVersion = versionMatcher.find() ? versionMatcher.group() : '1.0'

        file(distDir).mkdirs()

        // jpackage's --input scans the WHOLE install dir recursively for jars and puts every
        // one of them on the launched app's classpath -- including distIde's normally-bundled
        // per-platform Java 8 JRE folders (tools/jre, tools/jreLinux, tools/jreMac), which each
        // carry their own rt.jar/jce.jar AND, critically, ext/jfxrt.jar (JavaFX 8's OWN
        // javafx.* classes). Left in place, those end up on the classpath side by side with
        // the real javafx-*-11.0.2-mac jars added below -- a mixed-version JavaFX split-package
        // conflict that was observed to hang the app silently right after MainForm starts
        // loading, with no exception and no window, rather than failing loudly. tools/jre11Mac
        // doesn't need to be inside --input either: the runtime is supplied separately via
        // --runtime-image below.
        delete "$installDir/tools/jre"
        delete "$installDir/tools/jreLinux"
        delete "$installDir/tools/jreMac"
        delete "$installDir/tools/jre11Mac"
        delete "$installDir/tools/Launch4j"
        delete "$installDir/tools/Launch4jLinux"

        copy {
            from configurations.javaFx11Runtime
            into "$installDir/lib"
        }

        exec {
            commandLine jpackageBin,
                    '--type', 'dmg',
                    '--name', 'DevelNext-Java11',
                    '--input', installDir,
                    '--main-jar', 'DevelNext.jar',
                    '--runtime-image', "$project.rootDir/develnext-tools/jre11Mac",
                    '--icon', "$project.rootDir/develnext/launcher/DevelNext.icns",
                    '--mac-package-identifier', 'org.develnext.ide',
                    '--app-version', appVersion,
                    '--dest', distDir
        }
    }
}

task distAll(dependsOn: ['distIdeWindowsSetup', 'distIdeLinuxSetup']) {

}